name: nia_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/bg.png
    - assets/icons/google.png
    - assets/icons/facebook.png
    - assets/icons/instagram.png
    - assets/icons/linkedin.png
    - assets/icons/x.png
